### ISSUE TITLE
app is none

### ISSUE THREAD

**Issue by fpf3** [vistafan12/discord-lite#2]
When trying to run, I get the following error:

```
app.on('window-all-closed', function() {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/home/fredo/git/discord-lite/main.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

shell returned 1
```

**Comment by zxsleebu** [comment]
Try to use a older Node.Js verison

**Comment by earwigsinyourveins** [comment]
is this project dead?

**Comment by vanishare** [comment]
what version should it be?

**Comment by vadimsdev** [comment]
I`m using the Node.js version 12.14.1 LTS, and I have the same error.

**Comment by namzop** [comment]
it doesn't work guys
